import type { RoleCode } from './enums.js';

/**
 * Permission catalogue and role matrix — the single source for docs/security.md §3.
 * The API guard, the seed (roles/permissions tables) and the web UI all read from here.
 */
export const PERMISSIONS = [
  'users:read',
  'users:manage',
  'audit:read',
  'settings:manage',
  'clients:read',
  'clients:write',
  'manpower-requests:read',
  'manpower-requests:write',
  'manpower-requests:approve',
  'jobs:read',
  'jobs:write',
  'jobs:publish',
  'candidates:read',
  'candidates:write',
  'applications:read',
  'applications:transition',
  'interviews:write',
  'interview-feedback:write',
  'offers:read',
  'offers:write',
  'offers:approve',
  'employees:read',
  'employees:write',
  'documents:read',
  'documents:read-identity',
  'documents:write',
  'onboarding:read',
  'onboarding:write',
  'onboarding-templates:manage',
  'deployments:read',
  'deployments:write',
  'timesheets:read',
  'timesheets:write',
  'timesheets:approve',
  'invoices:read',
  'invoices:write',
  'workflows:manage',
  'automations:manage',
  'ai:use',
  'ai:ask-data',
  'ai:usage-read',
  'reports:read',
  'reports:export',
  'webhooks:manage',
  'integrations:manage',
  'system:health-detail',
  'notifications:read',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

/**
 * Role → permissions. "S" (scoped) cells in security.md are granted here; the data scope is
 * applied by each service (security.md §4).
 */
export const ROLE_PERMISSIONS: Record<RoleCode, readonly Permission[]> = {
  SUPER_ADMIN: PERMISSIONS,
  HR_MANAGER: [
    'users:read',
    'clients:read',
    'manpower-requests:read',
    'manpower-requests:write',
    'manpower-requests:approve',
    'jobs:read',
    'jobs:write',
    'jobs:publish',
    'candidates:read',
    'candidates:write',
    'applications:read',
    'applications:transition',
    'interviews:write',
    'interview-feedback:write',
    'offers:read',
    'offers:write',
    'offers:approve',
    'employees:read',
    'employees:write',
    'documents:read',
    'documents:read-identity',
    'documents:write',
    'onboarding:read',
    'onboarding:write',
    'onboarding-templates:manage',
    'deployments:read',
    'deployments:write',
    'timesheets:read',
    'timesheets:write',
    'ai:use',
    'ai:ask-data',
    'reports:read',
    'reports:export',
    'notifications:read',
  ],
  RECRUITER: [
    'manpower-requests:read',
    'jobs:read',
    'candidates:read',
    'candidates:write',
    'applications:read',
    'applications:transition',
    'interviews:write',
    'offers:read',
    'offers:write',
    'documents:read',
    'documents:write',
    'ai:use',
    'reports:read',
    'notifications:read',
  ],
  ACCOUNT_MANAGER: [
    'clients:read',
    'clients:write',
    'manpower-requests:read',
    'manpower-requests:write',
    'jobs:read',
    'employees:read',
    'onboarding:read',
    'deployments:read',
    'deployments:write',
    'timesheets:read',
    'invoices:read',
    'reports:read',
    'reports:export',
    'notifications:read',
  ],
  HIRING_MANAGER: [
    'jobs:read',
    'candidates:read',
    'applications:read',
    'interview-feedback:write',
    'offers:read',
    'offers:approve',
    'ai:use',
    'notifications:read',
  ],
  FINANCE: [
    'clients:read',
    'employees:read',
    'deployments:read',
    'timesheets:read',
    'timesheets:approve',
    'invoices:read',
    'invoices:write',
    'ai:ask-data',
    'reports:read',
    'reports:export',
    'notifications:read',
  ],
  EMPLOYEE: [
    'employees:read',
    'employees:write',
    'documents:read',
    'documents:read-identity',
    'documents:write',
    'onboarding:read',
    'onboarding:write',
    'deployments:read',
    'timesheets:read',
    'timesheets:write',
    'notifications:read',
  ],
  CLIENT_USER: [
    'clients:read',
    'manpower-requests:read',
    'manpower-requests:write',
    'candidates:read',
    'applications:read',
    'deployments:read',
    'timesheets:read',
    'timesheets:approve',
    'invoices:read',
    'notifications:read',
  ],
};

export const ROLE_LABELS: Record<RoleCode, string> = {
  SUPER_ADMIN: 'Super Admin',
  HR_MANAGER: 'HR Manager',
  RECRUITER: 'Recruiter',
  ACCOUNT_MANAGER: 'Account Manager',
  HIRING_MANAGER: 'Hiring Manager',
  FINANCE: 'Finance',
  EMPLOYEE: 'Employee',
  CLIENT_USER: 'Client user',
};

/** Union of the permissions granted by a set of roles. */
export function permissionsForRoles(roles: readonly RoleCode[]): Permission[] {
  const set = new Set<Permission>();
  for (const role of roles) {
    for (const permission of ROLE_PERMISSIONS[role]) {
      set.add(permission);
    }
  }
  return [...set].sort();
}
